# -*- coding: utf-8 -*-
"""Desarrollo de predicados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fi2rVKl1NrcFzqxVRGcvZl2R-gt343xW
"""

#Universo
ESTUDIANTES = {"Daniel", "Jhonny", "Bravo"}
PROFESORES = {"DrGarcia", "DrMartinolli"}
CARRERAS = {"Informatica", "Electromecanica"}
MATERIAS = {"Conmutacion", "Calculo"}
BECAS = {"BecaAcademica", "BecaDeportiva"}
SEMESTRES = {"Semestre1", "Semestre2", "Semestre3"}
CALIFICACIONES = {70, 80, 90, 100}

#Hechos
estudiantes = {"Daniel", "Jhonny"}
profesores = {"DrGarcia", "DrMartinolli"}
estudia = {
    ("Daniel", "Informatica"),
    ("Jhonny", "Electromecanica"),
}
imparte = {
    ("DrGarcia", "Conmutacion"),
    ("DrMartinolli", "Calculo"),
}
aprobo = {
    ("Daniel", "Conmutacion"),
    ("Jhonny", "Calculo"),
}
tiene_beca = {
    ("Daniel", "BecaAcademica"),
    ("Bravo", "BecaDeportiva"),
}
calificacion = {
    ("Daniel", "Conmutacion", 100),
    ("Jhonny", "Calculo", 80),
}

#Predicados
def Estudiante(x):
    return x in ESTUDIANTES and x in estudiantes


def Profesor(x):
    return x in PROFESORES and x in profesores


def Estudia(x, y):
    return x in ESTUDIANTES and y in CARRERAS and (x, y) in estudia


def Imparte(x, y):
    return x in PROFESORES and y in MATERIAS and (x, y) in imparte


def Aprobo(x, y):
    return x in ESTUDIANTES and y in MATERIAS and (x, y) in aprobo


def TieneBeca(x, y):
    return x in ESTUDIANTES and y in BECAS and (x, y) in tiene_beca


def Calificacion(x, y, z):
    return (
        x in ESTUDIANTES
        and y in MATERIAS
        and z in CALIFICACIONES
        and (x, y, z) in calificacion
    )


#Consultass positivas y negativas
consultas = [
    ("Estudiante(Daniel)", Estudiante("Daniel")),
    ("Estudiante(Bravo)", Estudiante("Bravo")),
    ("Profesor(DrGarcia)", Profesor("DrGarcia")),
    ("Profesor(Daniel)", Profesor("Daniel")),
    ("Estudia(Daniel, Informatica)", Estudia("Daniel", "Informatica")),
    ("Estudia(Daniel, Electromecanica)", Estudia("Daniel", "Electromecanica")),
    ("Imparte(DrGarcia, Conmutacion)", Imparte("DrGarcia", "Conmutacion")),
    ("Imparte(DrGarcia, Calculo)", Imparte("DrGarcia", "Calculo")),
    ("Aprobo(Daniel, Conmutacion)", Aprobo("Daniel", "Conmutacion")),
    ("Aprobo(Daniel, Calculo)", Aprobo("Daniel", "Calculo")),
    ("TieneBeca(Daniel, BecaAcademica)", TieneBeca("Daniel", "BecaAcademica")),
    ("TieneBeca(Daniel, BecaDeportiva)", TieneBeca("Daniel", "BecaDeportiva")),
    ("Calificacion(Daniel, Conmutacion, 100)", Calificacion("Daniel", "Conmutacion", 100)),
    ("Calificacion(Daniel, Conmutacion, 70)", Calificacion("Daniel", "Conmutacion", 70)),
]

for consulta, resultado in consultas:
    print(f"{consulta} -> {resultado}")